###########
# site.title

title:    'CallMePro'
subtitle: 'CS 175: Project in AI (in Minecraft)'

baseurl: "CallMePro"
#baseurl: ""
url: "https://markmzy.github.io/CallMePro/index.html"

#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
